from collections.abc import Sequence
from typing import Protocol

from aioreactive import AsyncObservable


class Model[T](Protocol):
    @property
    def on_append(self) -> AsyncObservable[Sequence[T]]: ...

    def get(self, pos: int) -> T: ...
    def count(self) -> int: ...
    def is_empty(self) -> bool: ...
